#!/bin/bash
./build &> /dev/null

for c in ./tests/*.c; do ./compiler < "$c" &> "${c%?}"test.ast ; done
for t in ./tests/*.test; do diff "$t" ./"$t".ast ; done


if [ $? -ne 1 ]
then
  echo -e "\033[0;32m All Tests Passed!"
else
  echo -e "\033[0;31m Tests failed"
fi